# Generated by Django 4.2.6 on 2024-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ud', models.CharField(max_length=20)),
                ('date_register', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=35)),
                ('studio', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=40)),
                ('date_of_start', models.DateField(auto_now_add=True)),
                ('date_of_creation', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
    ]
