# Generated by Django 4.2.6 on 2024-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_of_start',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
