# Generated by Django 4.2.6 on 2024-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_film_date_of_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_of_creation',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
