# Generated by Django 4.2.6 on 2024-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_film_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
