# Generated by Django 4.2.6 on 2024-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_film_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52)),
                ('location', models.CharField(max_length=61)),
                ('street', models.CharField(max_length=52)),
                ('ur_name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('inn', models.CharField(max_length=10)),
                ('map', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
