# Generated by Django 4.2.11 on 2024-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cinema_delete_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='inn',
            field=models.CharField(max_length=15),
        ),
    ]
