# Generated by Django 4.2.11 on 2024-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cinema_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='street',
            field=models.CharField(max_length=72),
        ),
    ]
