# Generated by Django 4.2.11 on 2024-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cinema_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(max_length=72),
        ),
    ]
