# Generated by Django 4.2.11 on 2024-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cinema_ur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='ur_name',
            field=models.CharField(max_length=250),
        ),
    ]
